before_script:
  - "export PROJECT_DIR=/var/www/quiz-dictionary-app/"
  - "export BUILD_DIR=~/var/www/quiz-dictionary-app/tmp/${CI_PIPELINE_ID}"
  - "whoami"
  - "echo \"Current location:\" $PWD"
  - "python3 --version"
  - "pip3 --version"


build:
  stage: build
  script:
    - "rm -rf ${BUILD_DIR}"
    - "mkdir -p ${BUILD_DIR}"
    - "cp -r `pwd`/* ${BUILD_DIR}/"
    - "cp -r `pwd`/.git ${BUILD_DIR}/"
    - "cd $BUILD_DIR"
    - "python3 -m venv venv"
    - "source venv/bin/activate"
    - "pip3 install -r requirements.txt"
#  tags:
#    - quiz_dict
  only:
    - build

deploy:
  stage: deploy
  script:
    - "rm -rf ${PROJECT_DIR}"
    - "mkdir -p ${PROJECT_DIR}"
    - "echo $CI_PROJECT_DIR"
    - "cp -r $CI_PROJECT_DIR/* ${PROJECT_DIR}/"
    - "cp -r $CI_PROJECT_DIR/.git ${PROJECT_DIR}/"
    - "pip3 install -r requirements.txt"
    - "cd $PROJECT_DIR"
    - "systemctl restart gunicorn.service"
  only:
    - master
#  tags:
#    - quiz_dict
