# Generated by Django 3.2.9 on 2021-11-22 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_alter_dictionarymodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionarymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
